### ISSUE TITLE
Support checking symbols in running perl process

### ISSUE THREAD

**Issue by calid** [avenj/dzil-ffi-checklib#1]
@avenj I'm not sure it's feasible to add this to the CheckLib plugin, but I have a particular use case where the plugin can _almost_ do what I need, but not quite.

Basically, using `ZMQ::FFI` on BSD with an unthreaded perl isn't safe.  see calid/zmq-ffi/issues/13 and plicease/FFI-Platypus/issues/51 for details.  That being the case I want to check for the `pthread_self` symbol (which the CheckLib plugin can do), but I want to check for it _in the running perl process_, e.g.:

``` perl
use strict;
use warnings;
use 5.010;
use FFI::Platypus;

my $ffi = FFI::Platypus->new;
$ffi->lib( undef );

if($ffi->find_symbol('pthread_self'))
{
  say "have pthreads";
}
else
{
  say "no pthreads";
}
```

Is it possible to add a hook to the plugin to accomplish this?  Thanks!

**Comment by avenj** [comment]
Hmm. I'm not sure of a way to do this without a mandatory dep on FFI::Platypus (which doesn't mean I'm not considering it, but afaik FFI::CheckLib itself won't do this right now)

For the given use case, it seems maybe more appropriate to check Config.pm's $Config{usethreads} or so?

**Comment by calid** [comment]
Yeah, I considered that.  The only issue is if they've built a custom perl manually linked to pthread (but not compiled with the usethreads option), that's still good enough.  Helluva edge case I know, but checking for the symbol removes any ambiguity.

**Comment by calid** [comment]
Not a huge deal, easy enough to add a custom check using MakeMaker::Awesome (which is what I'm doing for now).

**Comment by avenj** [comment]
I started screwing around with this on a branch, but it seemed like something that maybe should live elsewhere. I haven't tested this at all yet, but perhaps something like: https://github.com/avenj/dzil-checkperlsymbols

**Comment by calid** [comment]
Awesome Jon, just gave it a try and it does exactly what I would expect.  I like the addition of `lacks_symbol`, useful.  I agree about putting the functionality into its own module/plugin.  A few potential tweaks:
- Should it be called `FFI::CheckPerlSymbols` to be consistent with `FFI::CheckLib`?
- The errors right now are a bit cryptic, how about something more explicit?  Maybe something like:

> Required native symbol 'required_sym' wasn't found in your perl interpreter, installation can't continue.

and

> Conflicting native symbol 'bad_sym' was found in your perl interpreter, installation can't continue.

However after asking you to do this, I'm now not sure I can get away from a custom block using `MakeMaker::Awesome` anyways.  I only want to do this check on BSD, and to your point about having a clean separation of concerns it would probably be wrong to add support for that kind of check in this plugin itself.

Do you know of any dzil magic where I can enable certain plugins only on particular platforms?  If so I'll definitely use this plugin... otherwise I guess I'm stuck with the `MakeMaker::Awesome` solution.

**Comment by avenj** [comment]
Not sure what the sensible way to make this platform-dependent would be, though ...

**Comment by avenj** [comment]
... and your comment loaded after I posted my previous wrt platform-specific checks ;-)

I think your current solution is the best thing there. I'll ponder further...

**Comment by avenj** [comment]
I pushed some changes to dzil-checkperlsymbols (edited, I slipped a 'ffi' in there -- Freudian?) to allow pattern matching against $^O in commit 332733e -- untested again (except for the basic Makefile.PL/Build.PL checks in t/).

I also changed the wording of the warn(), but (assuming this goes to CPAN) I'm undecided on dist name. It seems like this could be useful in esoteric cases for non-FFI applications (like Inline::C bits, maybe)

**Comment by calid** [comment]
@avenj doesn't the `FFI` in the module name refer to how it's implemented, not how it's used?  i.e. `FFI::CheckLib` vs `Devel::CheckLib` or `FFI::TinyCC` vs `C::TinyCompiler`.

**Comment by avenj** [comment]
Fair point, I can see where it's fuzzy. I tend to think of FFI::CheckLib as "check for callable libs and we don't care about headers" vs. Devel::CheckLib for "headers includable by XS" bits, but most everything else FFI::-y is "uses FFI"

Will sleep on it ;-)

**Comment by calid** [comment]
As long as you're trying to support skipping the sym checks, I think it would be useful to do something more generic than just an OS check.  I went ahead and created a branch that supports a `skip_if` option [here](http://github.com/calid/dzil-ffi-checklib/tree/skip-conditional) (as well as tests and updated docs).  The feature in action would look like this:

``` ini
[CheckPerlSymbols]
has_symbol = pthread_self
skip_if    = $^O !~ m/bsd/i
```

Let me know what you think.

**Comment by avenj** [comment]
I like it, but I'm not sure about a skip expression that applies to every symbol specified.

Commit 4e272c1 adds per-symbol conditional skip expressions; perhaps this is too awkward?

**Comment by calid** [comment]
Well, remember you can have multiple instances of a plugin.  So if you really need such granularity you could do:

``` ini
[CheckPerlSymbols / BsdCheck]
has_symbol = pthread_self
skip_if    = $^O !~ m/bsd/i

[CheckPerlSymbols / 64Check]
has_symbol = some_64_sym
skip_if    = $Config{archname} !~ m/x86_64/ 
```

**Comment by avenj** [comment]
Fair point; your solution is cleaner.

Next question: if you think you might use it, want maint? ;-) 
You'll likely use it more than I ... but I don't mind either way ;-)

**Comment by calid** [comment]
ha, sure that's not a problem.  as you say, probably makes sense since I'm the one who needs this...

unless you see something else that needs to get added I'll publish the `skip_if` version to CPAN as 0.01.  I'll be sure it lists you as author and myself as maintainer.

**Comment by avenj** [comment]
No worries, do what you like with it ;-)  Fun little poke at dzil, if you cut a release I'm cool with a mention in POD anywheres ...

**Comment by plicease** [comment]
This has been closed for a while, but I wanted to weigh in as the author of `FFI::CheckLib` and now the maintainer of `Dist::Zilla::Plugin::FFI::CheckLib` ( now living in https://github.com/Perl5-FFI/Dist-Zilla-Plugin-FFI-CheckLib ).

 1. As of 0.17, FFI::CheckLib now has the ability to check for symbols in found libraries, but I don't think this will work consistently with the `undef`, search current perl executable that `FFI::Platypus` can do.

 2. (regarding https://github.com/avenj/dzil-ffi-checklib/issues/1#issuecomment-84521649 ) the naming convention that I have always used is that  have `FFI::` as a prefix are for tools for writing FFI modules and modules that have a `::FFI` suffix are for modules that are implemented using FFI.  Others may have different conventions.  (Also `FFI::TinyCC` is a weird case, that I think fits both, but that is another story).
